Frontend component tests
Lambda-School-Labs/nutrition-tracker-fe pull request #32
Opened 2019-12-20 04:45 UTC by israelgonzalezb

# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Change Status

- [ ] Complete, tested, ready to review and merge
- [ ] Complete, but not tested (may need new tests)
- [ ] Incomplete/work-in-progress, PR is for discussion/feedback

# How Has This Been Tested?

- [ ] Test A
- [ ] Test B

# Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My code has been reviewed by at least one peer
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] There are no merge conflicts

2019-12-20 04:58 UTC, AlyssaSaez approved these changes
Thank you for your service

2019-12-21 02:02 UTC, dave-vazquez commented on src/components/FoodItem/index.js
>          <Route
there's some changes to code here that aren't tests?

2019-12-21 02:05 UTC, dave-vazquez requested changes
saw a few changes here to files that weren't tests, just want to be cautious before merging in

2019-12-24 06:04 UTC, dave-vazquez commented on src/setUpTests.js
> +  logger
I added this function back cause it doubled our passing tests, can always be removed if necessary

2019-12-24 06:05 UTC, dave-vazquez commented on src/setUpTests.js
> -import configureStore from "redux-mock-store";
delete one file, another one appears... delete that file, the other one appears 👻 👻 👻

2019-12-24 06:18 UTC, dave-vazquez commented
Okey-doke, this one looks ready to go.

2019-12-24 06:19 UTC, dave-vazquez approved these changes

2019-12-24 06:20 UTC, merged